# Notes in Chapter 3
1. computations happening in neural networks are typically
executed with 32-bit floating-point precision.
2. PyTorch expects indexing tensors to have a 64-bit integer data type. Creating a tensor with integers as arguments, such as using `torch.tensor([2, 2])`, will create a 64-bit integer tensor by default.
3. a small number of operations exist only as methods of the Tensor object. They are recognizable from a trailing underscore in their name, like `zero_`, which indicates that the method operates in place by modifying the input instead of creating a new output tensor
and returning it. Any method without the trailing underscore leaves the source tensor unchanged and instead returns a new tensor.
4. Some tensor operations in PyTorch only work on contiguous tensors, such as `view`.We can obtain a new contiguous tensor from a non-contiguous one using the `contiguous` method. The content of the tensor will be the same, but the stride will change, as will the storage.
5. Numpy array shares the same underlying buffer with the tensor storage.
6. While the default numeric type in PyTorch is 32-bit floating-point, for NumPy it is 64-bit. As discussed in section 3.5.2, we usually want to use 32-bit floating-points, so we need to make sure we have tensors of dtype torch.float after converting.

In [1]:
import torch
torch.__version__

'1.4.0'

In [2]:
torch.cuda.is_available()

True

In [8]:

points = torch.zeros(2, 3)
double_points = torch.zeros(2, 3, dtype=torch.float64)
int_points = torch.zeros(2, 3, dtype=torch.int)

default type is float32 and int32.

In [9]:
points.dtype

torch.float32

In [10]:
int_points.dtype

torch.int32

In [11]:
double_points.dtype

torch.float64

In [12]:
int64_points = int_points.to(torch.int64)
int64_points.dtype

torch.int64

In [13]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a.transpose(0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [14]:
points_gpu = points.cuda()
points_gpu

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [15]:
points_np = points.numpy()
points_np

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [21]:
points = torch.from_numpy(points_np)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
points

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [24]:
with open('data/points.t', 'wb') as f:
    torch.save(points, f)

In [27]:
with open('data/points.t', 'rb') as f:
    points = torch.load(f)
points

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Exercise


In [34]:
# exercise 1
a = torch.tensor(list(range(9)))
print(a.size(), a.storage_offset(), a.stride())

torch.Size([9]) 0 (1,)


In [40]:
# exercise 1.a
b = a.view(3, 3)
print('a.storage():', a.storage())
print('b.storage():', b.storage())
# share the same storage
id(a.storage()) == id(b.storage())

a.storage():  0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]
b.storage():  0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]


True

In [41]:
# exercise 1.b
c = b[1:, 1:]
print(c.size(), c.storage_offset(), c.stride())

torch.Size([2, 2]) 4 (3, 1)


In [42]:
# exercise 2.a
torch.cos(a)

RuntimeError: cos_vml_cpu not implemented for 'Long'

In [44]:
# exercise 2.b
torch.cos(a.float())

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [45]:
# exercise 2.c
d = a.float()
# in place function
torch.cos_(d)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])